version: '3.8'
services:
  app:
    image: "demo-poc-reactive:0.0.1-SNAPSHOT"
    extra_hosts: ['host.docker.internal:host-gateway']
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - MANAGEMENT_ENDPOINT_ENV_SHOW_VALUES=ALWAYS
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,env,prometheus
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411/api/v2/spans
    profiles:
      - observability
    depends_on:
      - redis
      - tempo
      - loki
      - prometheus
      - grafana
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
  tempo:
    image: grafana/tempo
    container_name: tempo
    extra_hosts: ['host.docker.internal:host-gateway']
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo-local.yaml:/etc/tempo.yaml:ro
      - ./tempo-data:/tmp/tempo
    profiles:
      - observability
    ports:
      - "3200:3200"   # tempo
      - "14268"  # jaeger ingest
      - "9411:9411" # zipkin
  loki:
    image: grafana/loki
    container_name: loki
    extra_hosts: ['host.docker.internal:host-gateway']
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    profiles:
      - observability
    depends_on:
      - tempo
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
  prometheus:
    image: prom/prometheus
    extra_hosts: ['host.docker.internal:host-gateway']
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    profiles:
      - observability
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    extra_hosts: ['host.docker.internal:host-gateway']
    volumes:
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - loki
      - prometheus
      - tempo
    profiles:
      - observability
    ports:
      - "3000:3000"